name: Visit website using Firefox

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Enter the URL of the website to visit"
        required: true

jobs:
  visit-website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
    steps:
    - name: Install python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install fake_useragent
    - name: Use Firefox to visit website
      env:
        DISPLAY: :99.0
        MOZ_HEADLESS: 1
      run: |
        sudo apt-get install -y firefox xvfb
        resolution=$(shuf -n 1 -e "3840x2160" "2560x1440" "1920x1080")
        Xvfb :99 -screen 0 ${resolution} > /dev/null 2>&1 &
        echo 'Starting Firefox ...'
        firefox --version
        firefox --headless --no-remote --marionette --setDefaultBrowser --user-agent "$(python3 -c 'from fake_useragent import UserAgent; print(UserAgent().random)')" ${{ inputs.url }}
        duration=$(shuf -n 1 -e "5m" "10m" "15m" "20m" "25m" "30m" "35m" "40m" "45m" "50m" "55m" "60m")
        echo "Sleeping for ${duration} before closing the browser"
        sleep ${duration}
        pkill firefox
